# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfcd2399304a9cae1c37dbcfc4e8bed90042bc21295d1783e635be4137829a4cb2f8aac00f633e6f5224821e2c09286769abdb7b90a24090ca423ac61f887b3c

test:
  secret_key_base: 7c5cb5db41534c6f9780b266eeff39479754d32ea2753c6b1100061722da8fc1591673a15814675cd22eb056f4535b844b3e2a0b29fd20a82518e28b391e1dad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
